 services:
  blog-server:
    container_name: blog-node
    build: node/
    restart: unless-stopped
    volumes:
      - ./node:/node
      - /node/node_modules
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PASSWORD_PEPPER: "TEMPORARY_PEPPER"
      TOTP_ENCRYPTION_KEY: "5f8d3c9a7b2e4d1f6a9c0e3b8d7f2a1c4e6b9d0f3a2c7e8b1d4f6a9c0e3b8d7f" # Temporary
      DB_HOST: blog-postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    # Ensure that postgres is running before starting up node
    depends_on:
      blog-db:
        condition: service_healthy 

  blog-db:
    container_name: blog-postgres
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb # set shared memory limit when using docker-compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./postgres/scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 1s
      retries: 5
      timeout: 2s
